export const TRANSACTIONAL_EMAIL_TEMPLATES = [
  "welcome-mentee",
  "welcome-subscriber",
  "welcome-teacher",
  "welcome-student",
  "welcome-forum-moderator",
  "welcome-sub-admin",
  "email-confirmation",
  "password-reset",
  "subscription-confirmation",
  "subscription-renewal-notification",
  "subscription-cancellation-confirmation",
  "physical-event-rsvp-confirmation",
  "digital-event-link-delivery",
  "swag-order-confirmation",
  "swag-order-status-update",
  "donation-receipt",
  "gift-card-delivery",
  "mentor-application-acknowledgment",
  "scholarship-application-acknowledgment",
  "teacher-invite",
  "student-invite",
  "forum-moderator-invite",
  "sub-admin-invite",
  "contact-confirmation",
  "school-demo-confirmation",
  "scholarship-inquiry-confirmation",
  "data-access-confirmation",
  "data-deletion-confirmation",
  "admin-broadcast",
  "account-deactivation-confirmation",
] as const;

export type TransactionalEmailTemplate =
  (typeof TRANSACTIONAL_EMAIL_TEMPLATES)[number];
